apiVersion: ENC[AES256_GCM,data:2ww=,iv:4MTrrvlBSMlMqKY9ojCs9m45D9nMOru5Tqc9uCKKsdM=,tag:IbjKhYQ8NKJLKTOPBSiwLg==,type:str]
kind: ENC[AES256_GCM,data:19aLDKrd,iv:xIAo8GxsAdesUzc2+Cpf4wDeDFpgFCdG1CxA+UDZ/eA=,tag:H0SBdkpOljxDy0d5h2jK6Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XjceXvJH8fVvC3hroNuU,iv:aI4NNpGQDv80moCViWedD2IkrYjS9fJO+EBi02cFiaE=,tag:a5WJkANpR975oSqdiziTxA==,type:str]
    namespace: ENC[AES256_GCM,data:bdA7OpWeW9T0,iv:3Gg5e4ty6cSOcmmqpZ8V9cXehEnCLsEwoonVlovkPNI=,tag:0DEXtrW6QHy9eKYHYA/DOA==,type:str]
type: ENC[AES256_GCM,data:nkkm3Hvz,iv:G7FjF3hJNfJPQ/oPsZeyzxGvEgq85Jn7K5pP2ACSgQs=,tag:3mTTTpJ1+my98/S6T+sLSg==,type:str]
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:JH+hjOgqw/N9PCyUM8E=,iv:/Y5STraut55KC2dbVluNAnGo5nCmNVtyj+c8/EdznMo=,tag:eROcsRWLC9YkHSeCPfqn+A==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:ec8/PeI2CSFN99sA1iIqnJjFhck=,iv:lTl5byUUQFfpJfqoti80++rbnifZggXeMOPf5Nh0tKc=,tag:bZfQSVeSRR9JDoNgOhlQLg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:SoTew/bTAQlN9Q==,iv:bFqvHILpXbVJ7BmGRlo3CR5Ae85MfvkPrit6wXAAFgA=,tag:5EpfRz9u+qipYbpf7a/emQ==,type:str]
sops:
    age:
        - recipient: age1k7kj2dzn5ywcp0h03k03wdvceclw7ac7wshq3k97uxtk99l6kysqdj53sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBocjY1enk3K2hhQ3BYUzRC
            NjdaeitidUFHQnFWN0QrT1lhd0U5NFRHeXdBCks1bSt1TjdOY3ByeUFaKzNIeGVJ
            QndYU3BVVUhhekpSTC9Lc0RXN2ljd0kKLS0tIFBFbWIxTUladXhoRnppbm9yeWJL
            MU1IVUp6THd0ekxsVUpZdkZKMndEeDQK/iM2SThYmF1i+xDuKx9Sb0Vvv3Snr9sy
            2EP0CiAVtiXbbyybkL1NpJO4oZURXF84wuvbl2JTfobOiH3D05kSzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T16:23:32Z"
    mac: ENC[AES256_GCM,data:jrWNMvCHZPwQqcf/0SL0sDXshT8gIQJhA1zCtY+zUPfrmb5zZSKCpyRVAmZCSHkQ9kgZo4H1OFSIMIkqfIGLrGzQpBA9lx2Ez0kLnVKPPWp4fqrQYK0D4PlqZxKz9QUgL1LpYrhwZtofIkdtI7y5dSXjS0A4cYkQBE7sUq4gcSs=,iv:ZOzHB7MbX/Qb1s8ak/QE0ETZBjm5r/L0SGOXFp3pvEw=,tag:LUuLEPDihnV8UN5qDqzlUg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
