apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: databases
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:X3ZLEFSwonTqLK3leFE=,iv:2Sbgld+9N3KtSWmniC/EHEKFExOba/cB+/1/k/xDcrY=,tag:CS3ZFNDZlHEbPIoBZcxkLQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:APwiQbkW5zYNKzxOGJ8LyXZIpxw=,iv:H/GzYz9DSztKZ2nT/0vAENW4pGDUFYNVP0KjWf87xfc=,tag:n90hvOgZ5XzTpXX0kjmraw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:R0wAnN+60rqJAA==,iv:AaT8ZYR7t9/8SlkC0Mm2ZCZHFG/aD8hixcxT0pSX01o=,tag:+n9IHTNaEv3KZEYesxUCXw==,type:str]
sops:
    age:
        - recipient: age1k7kj2dzn5ywcp0h03k03wdvceclw7ac7wshq3k97uxtk99l6kysqdj53sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyWHVnQkNKc2tteWpVRFBv
            MjdiTnJnSzdqb0lnQ0lXampoRzBHczBYSUVRCk1KREVQYWRzZmJRaUZEcDJJVnZw
            a2pabUVtRjBDZnFmUTdURGF1WlNGSkkKLS0tIDE4dkI1Rll5R082OWFFRVhZcjRW
            Q2FXLytURDltc0xRaHJMNHVCZHk3T3cKJ7dOvlcQFeguXSV1mOGwtbSKfMvEFvDg
            vdEd97nZ3lNUF407mNMBFIyXKrsJPrrx/c2dzrgvwFkNdZ93kSzMbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T17:35:35Z"
    mac: ENC[AES256_GCM,data:oIczS2VEnBAZ0LzVtdYrarfC71ESFDvlyqENHdRZCitHmlicoijwnNJjB9inUmDeiGzyzPqWMocmuru6bjtkIwYsp7rMxomwsSJtRMUBxq7fMnGG97OtzrRkP3mE9IzQra7A/p3iqsCpnW7b63adx+X5ehmZ7K/KHEK3PWlHTDs=,iv:VyEyJscRNQ8QQJf6stwuXHWPS2HsPW4pXIf1pfQF0XM=,tag:kWIsmeugarzTQH4oIJzmnQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
