apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: calico-node
  namespace: kube-system
spec:
  template:
    spec:
      initContainers:
      - name: install-cni
        env:
        - name: KUBERNETES_SERVICE_HOST
          value: "kubernetes.default.svc.cluster.local"
        - name: KUBERNETES_SERVICE_PORT
          value: "443"
      containers:
      - name: calico-node
        image: docker.io/calico/node:v3.28.0
        env:
        - name: IP_AUTODETECTION_METHOD
          value: "interface=eth*"
        - name: CALICO_IPV4POOL_CIDR
          value: "10.244.0.0/16"
        - name: CALICO_IPV4POOL_VXLAN
          value: "Always"
        - name: FELIX_BPFENABLED
          value: "false"
