---
# DucksNest Homelab Ansible Inventory

all:
  vars:
    # 공통 변수들
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/ducksnest-key.pem
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
    # Tailscale 설정
    tailscale_auth_key: "{{ vault_tailscale_auth_key }}"
    headscale_url: "https://{{ hostvars[groups['jenkins_headscale'][0]]['ansible_host'] }}"
    
    # 공통 환경 변수
    homelab_env: "production"
    timezone: "Asia/Seoul"

  children:
    aws_instances:
      children:
        jenkins_headscale:
          hosts:
            jenkins-server:
              ansible_host: "{{ jenkins_public_ip }}"  # Terraform output에서 가져올 예정
              private_ip: "{{ jenkins_private_ip }}"
              tailscale_hostname: "ducksnest-jenkins"
              roles:
                - jenkins
                - headscale
                - ansible_control
        
        k8s_control_plane:
          hosts:
            k8s-control-plane:
              ansible_host: "{{ k8s_cp_public_ip }}"  # Terraform output에서 가져올 예정
              private_ip: "{{ k8s_cp_private_ip }}"
              tailscale_hostname: "ducksnest-controlplane"
              roles:
                - k8s_master
                - tailscale_client
    
    # 온프레미스 NixOS 워커 노드들 (추후 추가)
    onprem_workers:
      vars:
        ansible_user: root  # NixOS는 보통 root 사용
      hosts:
        # laptop-old:
        #   ansible_host: "tailscale_ip_of_laptop_old"
        #   tailscale_hostname: "ducksnest-worker-old"
        # laptop-ultra:  
        #   ansible_host: "tailscale_ip_of_laptop_ultra"
        #   tailscale_hostname: "ducksnest-worker-ultra"
    
    # 그룹별 역할 정의
    jenkins:
      hosts:
        jenkins-server:
    
    headscale:
      hosts:
        jenkins-server:
    
    k8s_masters:
      hosts:
        k8s-control-plane:
    
    k8s_workers:
      hosts:
        # laptop-old:
        # laptop-ultra:
    
    tailscale_clients:
      hosts:
        k8s-control-plane:
        # laptop-old:
        # laptop-ultra: