---
# Kubernetes Control Plane 서버 전용 설정

# Kubernetes Control Plane 설정
k8s_role: "master"
k8s_init_cluster: true

# kubeadm 설정
kubeadm_config:
  api_server_extra_args:
    audit-log-maxage: "30"
    audit-log-maxbackup: "3"
    audit-log-maxsize: "100"
  
  controller_manager_extra_args:
    bind-address: "0.0.0.0"
  
  scheduler_extra_args:
    bind-address: "0.0.0.0"
  
  etcd_extra_args:
    listen-metrics-urls: "http://0.0.0.0:2381"

# CNI 설정 (Flannel)
cni_plugin: "flannel"
flannel_version: "0.25.6"
flannel_iface: "tailscale0"  # Tailscale 인터페이스 사용

# Kubernetes 클러스터 설정
cluster_name: "ducksnest-cluster"
service_subnet: "{{ kubernetes_service_cidr }}"
pod_subnet: "{{ kubernetes_pod_cidr }}"

# etcd 설정
etcd_data_dir: "/var/lib/etcd"
etcd_backup_dir: "/opt/etcd-backup"

# 인증서 설정
k8s_cert_extra_sans:
  - "{{ ansible_host }}"           # Public IP
  - "{{ private_ip }}"             # Private IP  
  - "{{ tailscale_ip | default('') }}"  # Tailscale IP (동적으로 설정됨)
  - "{{ homelab_domain }}"
  - "api.{{ homelab_domain }}"

# kubelet 설정
kubelet_extra_args:
  - "--node-ip={{ tailscale_ip | default(private_ip) }}"
  - "--cluster-dns=10.96.0.10"
  - "--cluster-domain=cluster.local"

# UFW 규칙 (Kubernetes Control Plane 전용)
ufw_rules:
  - { rule: "allow", port: "22", proto: "tcp" }          # SSH
  - { rule: "allow", port: "6443", proto: "tcp" }        # Kubernetes API
  - { rule: "allow", port: "2379:2380", proto: "tcp" }   # etcd
  - { rule: "allow", port: "10250", proto: "tcp" }       # kubelet API
  - { rule: "allow", port: "10259", proto: "tcp" }       # kube-scheduler
  - { rule: "allow", port: "10257", proto: "tcp" }       # kube-controller-manager
  - { rule: "allow", port: "41641", proto: "udp" }       # Tailscale

# 모니터링 설정 
monitoring_enabled: true
prometheus_node_exporter_port: 9100
kubelet_metrics_port: 10255

# 백업 설정
etcd_backup_enabled: true
etcd_backup_schedule: "0 2 * * *"  # 매일 새벽 2시
etcd_backup_retention_days: 7

# 로깅 설정
audit_log_enabled: true
audit_log_path: "/var/log/audit.log"
audit_log_maxage: 30
audit_log_maxbackup: 3
audit_log_maxsize: 100